config/routes.rb
Try::Application.routes.draw do
  resources :vjs

   root :to => 'vjs#index'

end

app/models/vj.rb
class Vj < ActiveRecord::Base
  attr_accessible :age, :name, :photo

  has_attached_file :photo, :styles => { :small => "150x150>" },
                    :url  => "/assets/products/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/products/:id/:style/:basename.:extension"

  validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/vjs_controller.rb
class VjsController < ApplicationController
  # GET /vjs
  # GET /vjs.json
  def index
    @sai = Vj.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vjs }
    end
  end

  # GET /vjs/1
  # GET /vjs/1.json
  def show
    @vj = Vj.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vj }
    end
  end

  # GET /vjs/new
  # GET /vjs/new.json
  def new
    @vj = Vj.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vj }
    end
  end

  # GET /vjs/1/edit
  def edit
    @vj = Vj.find(params[:id])
  end

  # POST /vjs
  # POST /vjs.json
  def create
    @vj = Vj.new(params[:vj])

    respond_to do |format|
      if @vj.save
        format.html { redirect_to @vj, notice: 'Vj was successfully created.' }
        format.json { render json: @vj, status: :created, location: @vj }
      else
        format.html { render action: "new" }
        format.json { render json: @vj.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vjs/1
  # PUT /vjs/1.json
  def update
    @vj = Vj.find(params[:id])

    respond_to do |format|
      if @vj.update_attributes(params[:vj])
        format.html { redirect_to @vj, notice: 'Vj was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vj.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vjs/1
  # DELETE /vjs/1.json
  def destroy
    @vj = Vj.find(params[:id])
    @vj.destroy

    respond_to do |format|
      format.html { redirect_to vjs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vjs_helper.rb
module VjsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Try</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/vjs/_form.html.erb
<%= form_for(@vj) do |f| %>
  <% if @vj.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vj.errors.count, "error") %> prohibited this vj from being saved:</h2>

      <ul>
      <% @vj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :vj %><br />
    <%= f.file_field :photo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vjs/edit.html.erb
<h1>Editing vj</h1>

<%= render 'form' %>

<%= link_to 'Show', @vj %> |
<%= link_to 'Back', vjs_path %>

app/views/vjs/index.html.erb
<h1>Listing vjs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th>Report</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sai.each do |vj| %>
  <tr>
    <td><%= vj.name %></td>

<hr>
<%= params.inspect%>
<hr>


    <td><%= vj.age %></td>
    <td><%= image_tag vj.photo ,:height => 20,:id => "d" ,:onclick => "s()"%></td>
    <td><%= link_to 'Show', vj %></td>
    <td><%= link_to 'Edit', edit_vj_path(vj) %></td>
    <td><%= link_to 'Destroy', vj, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />
<p style="color:red">ssss</p>
<%= link_to 'New Vj', new_vj_path %>

<% Time.now.strftime("%S")%>

<hr>

<p id="d" onclick="f()">sssssssss</p>

<script type="text/javascript">
 function s (argument) {
   // body...
document.getElementById('d').height = 89
 }
 
</script>

app/views/vjs/new.html.erb
<h1>New vj</h1>

<%= render 'form' %>

<%= link_to 'Back', vjs_path %>

app/views/vjs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @vj.name %>
</p>

<p>
  <b>Age:</b>
  <%= @vj.age %>
</p>

<p>
  <b>Report:</b>
  <%= image_tag @vj.photo,:height=>50, :id=>'demo',:onclick => "s()" %>
</p>

<p id="demo" onclick="s()">ssssssssssssss</p>
<%= link_to 'Edit', edit_vj_path(@vj) %> |
<%= link_to 'Back', vjs_path %>

<script type="text/javascript">

 

document.getElementById('demo').style.color = 'red'



</script>